### ISSUE TITLE
Precision setting is broken with cm units

### ISSUE THREAD

**Issue by paulkaplan** [shapeoko/makercam#5]
When you switch to cm from in, the 'precision' setting that should set the number of digits in each number gives very erratic results. The default setting (0.00257mm or something) is processed as 0.00001 instead (I think because of the number of digits, rather than the actual value), and if you change it to say 0.001 you get some numbers that look correct but some that look like
G2 X189.811 Y145.108 I3.809 J0.9610000000000001

this comes up when processing circles on GRBL as it overflows the buffer easily
G2 X189.90800000000002 Y146.883 I3.9050000000000002 J-0.42700000000000005

**Comment by mattbornski** [comment]
+1 bump for this issue.  This is a fairly big obstacle for me.  Anybody working on it already?  Don't want to duplicate work.

**Comment by paulkaplan** [comment]
I fixed this with this PR: https://github.com/shapeoko/makercam/pull/6
